"""create_questionnaire_table

Revision ID: 5b52ee3666ba
Revises: ffdc0a98111c
Create Date: 2022-02-13 14:08:09.056771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b52ee3666ba'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exp_lvl', sa.Integer(), nullable=False),
    sa.Column('themes', sa.String(), nullable=False),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False, unique=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questionnaires')
    # ### end Alembic commands ###
